# Generated by Django 6.0.5 on 2026-05-27 12:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='RawUtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('meter_id', models.CharField(blank=True, max_length=50)),
                ('facility_name', models.CharField(blank=True, max_length=120)),
                ('billing_start_date', models.CharField(blank=True, max_length=50)),
                ('billing_end_date', models.CharField(blank=True, max_length=50)),
                ('usage_value', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('usage_unit', models.CharField(blank=True, max_length=20)),
                ('tariff_type', models.CharField(blank=True, max_length=50)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('raw_row', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.importbatch')),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedUtilityRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_id', models.CharField(max_length=50)),
                ('facility_name', models.CharField(max_length=120)),
                ('billing_start', models.DateField(blank=True, null=True)),
                ('billing_end', models.DateField(blank=True, null=True)),
                ('usage_kwh', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('tariff_type', models.CharField(blank=True, max_length=50)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, max_length=10)),
                ('supplier_name', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('import_batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingest.importbatch')),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingest.rawutilityrecord')),
            ],
        ),
        migrations.CreateModel(
            name='ValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=10)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='ingest.normalizedutilityrecord')),
            ],
        ),
    ]
