# Generated by Django 6.0.5 on 2026-05-28 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0002_unit_normalization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RawSAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('row_number', models.PositiveIntegerField()),
                ('raw_data', models.JSONField()),
                ('ingested_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NormalizedSAPRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material_number', models.CharField(blank=True, max_length=50)),
                ('plant_code', models.CharField(blank=True, max_length=50)),
                ('vendor_id', models.CharField(blank=True, max_length=50)),
                ('vendor_name', models.CharField(blank=True, max_length=200)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('invoice_number', models.CharField(blank=True, max_length=100)),
                ('fuel_type', models.CharField(blank=True, max_length=50)),
                ('original_quantity', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('original_unit', models.CharField(blank=True, max_length=20)),
                ('normalized_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=14, null=True)),
                ('normalized_unit', models.CharField(blank=True, default='liters', max_length=20)),
                ('total_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('cost_per_unit', models.DecimalField(blank=True, decimal_places=4, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='USD', max_length=10)),
                ('country', models.CharField(blank=True, max_length=50)),
                ('location_city', models.CharField(blank=True, max_length=100)),
                ('location_state', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('locked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sap_approvals', to=settings.AUTH_USER_MODEL)),
                ('raw_record', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='normalized', to='ingest.rawsaprecord')),
            ],
        ),
        migrations.CreateModel(
            name='SAPApprovalLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected'), ('locked', 'Locked for Audit'), ('unlocked', 'Unlocked'), ('note_added', 'Note Added')], max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('previous_status', models.CharField(blank=True, max_length=20)),
                ('new_status', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_logs', to='ingest.normalizedsaprecord')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SAPImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('upload_time', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='processing', max_length=20)),
                ('total_records', models.PositiveIntegerField(default=0)),
                ('failed_records', models.PositiveIntegerField(default=0)),
                ('suspicious_records', models.PositiveIntegerField(default=0)),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='rawsaprecord',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='raw_records', to='ingest.sapimportbatch'),
        ),
        migrations.AddField(
            model_name='normalizedsaprecord',
            name='import_batch',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='normalized_records', to='ingest.sapimportbatch'),
        ),
        migrations.CreateModel(
            name='SAPValidationIssue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(choices=[('error', 'Error'), ('warning', 'Warning')], max_length=10)),
                ('issue_type', models.CharField(choices=[('missing_plant', 'Missing Plant Code'), ('invalid_date', 'Invalid Date'), ('unknown_vendor', 'Unknown Vendor'), ('negative_amount', 'Negative Amount'), ('invalid_unit', 'Invalid Unit'), ('duplicate_invoice', 'Duplicate Invoice'), ('price_spike', 'Price Spike Detected'), ('quantity_anomaly', 'Quantity Anomaly'), ('suspicious_vendor', 'Suspicious Vendor Activity')], max_length=30)),
                ('message', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sap_issues', to='ingest.normalizedsaprecord')),
            ],
        ),
    ]
